/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int addop = 5;
  /** RegularExpression Id. */
  int keyw = 6;
  /** RegularExpression Id. */
  int keywIf = 7;
  /** RegularExpression Id. */
  int keywElse = 8;
  /** RegularExpression Id. */
  int keywLoop = 9;
  /** RegularExpression Id. */
  int type = 10;
  /** RegularExpression Id. */
  int identifier = 11;
  /** RegularExpression Id. */
  int num = 12;
  /** RegularExpression Id. */
  int negop = 13;
  /** RegularExpression Id. */
  int relop = 14;
  /** RegularExpression Id. */
  int assignop = 15;
  /** RegularExpression Id. */
  int mulop = 16;
  /** RegularExpression Id. */
  int begin = 17;
  /** RegularExpression Id. */
  int end = 18;
  /** RegularExpression Id. */
  int openparen = 19;
  /** RegularExpression Id. */
  int closeparen = 20;
  /** RegularExpression Id. */
  int semicolon = 21;
  /** RegularExpression Id. */
  int comma = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<addop>",
    "<keyw>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "<type>",
    "<identifier>",
    "<num>",
    "\"!\"",
    "<relop>",
    "\"=\"",
    "<mulop>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\",\"",
  };

}
